# Generated by Django 3.0.3 on 2020-04-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='geoPoint',
            new_name='geo_point',
        ),
    ]
