# Generated by Django 3.0.3 on 2020-03-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='members',
            new_name='member',
        ),
    ]
