# Generated by Django 3.0.3 on 2020-04-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('token_auth', '0005_auto_20200419_2044'),
        ('events', '0002_auto_20200413_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='events', to='common.Category'),
        ),
    ]
