# Generated by Django 3.0.3 on 2020-11-12 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20200610_1435'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('event', 'to_user', 'from_user')},
        ),
    ]
