# Generated by Django 3.0.3 on 2020-03-15 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20200315_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='member',
        ),
        migrations.AddField(
            model_name='invitation',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
