# Generated by Django 3.0.3 on 2020-04-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_request_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
