# Generated by Django 3.0.3 on 2020-03-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200223_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
