# Generated by Django 3.0.3 on 2020-04-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200427_1624'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='geopoint',
            table='geo_point',
        ),
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
    ]
