# Generated by Django 3.0.3 on 2020-03-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200327_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='geo_point',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.GeoPoint'),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=23),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=23),
        ),
    ]
