# Generated by Django 3.0.3 on 2020-03-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200310_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='geo_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.GeoPoint'),
        ),
    ]
