# Generated by Django 3.0.3 on 2020-05-03 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20200503_2149'),
        ('events', '0007_auto_20200427_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
