# Generated by Django 3.0.3 on 2020-05-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200503_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chat',
        ),
    ]
