# Generated by Django 3.0.3 on 2020-03-27 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200327_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='geo_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.GeoPoint'),
        ),
    ]
