# Generated by Django 3.0.3 on 2020-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200310_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', through='events.Categorization', to='events.Category'),
        ),
    ]
