# Generated by Django 3.0.3 on 2020-05-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200509_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='decision',
            field=models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('DECLINE', 'DECLINE'), ('NO_ANSWER', 'NO_ANSWER')], default='NO_ANSWER', max_length=16),
        ),
    ]
