# Generated by Django 3.0.3 on 2020-05-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200517_2327'),
        ('events', '0011_auto_20200509_1712'),
    ]

    operations = [
    ]
