# Generated by Django 3.0.3 on 2020-03-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200328_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='geo_point',
            new_name='geoPoint',
        ),
    ]
