# Generated by Django 3.0.3 on 2020-03-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20200328_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='geoPoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.GeoPoint'),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='address',
            field=models.TextField(),
        ),
    ]
