# Generated by Django 3.0.3 on 2020-03-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20200329_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopoint',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
