# Generated by Django 3.0.3 on 2020-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20200330_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='decision',
            field=models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('DECLINE', 'DECLINE'), ('NO_ANSWER', 'NO_ANSWER')], default='DECLINE', max_length=10),
        ),
    ]
