# Generated by Django 3.0.3 on 2020-03-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20200330_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='events', to='events.Category'),
        ),
    ]
