# Generated by Django 3.0.3 on 2020-04-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20200406_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='from_user',
        ),
    ]
