
stages:
  - build
  - test
  - deploy
  - remove

build:
  stage: build
  script:
    # TODO: make serviceAccountKey.json
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run app python manage.py test -v=2

deploy:
  stage: deploy
  script:
    - docker-compose up -d

remove:
  stage: remove
  when: manual
  script:
    - docker-compose down

