
stages:
  - build
  - deploy
  - remove

build:
  stage: build
  script:
    - docker-compose build

deploy:
  stage: deploy
  script:
    - docker-compose up -d

remove:
  stage: remove
  script:
    - docker-compose down
  when: manual

