# Generated by Django 3.0.3 on 2020-05-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
