# Generated by Django 3.0.3 on 2020-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0003_auto_20200528_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.IntegerField(blank=True, default=235234),
            preserve_default=False,
        ),
    ]
