# Generated by Django 3.0.3 on 2020-05-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0004_auto_20200528_1907'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='confirmationcode',
            table='confirmation_code',
        ),
    ]
