# Generated by Django 3.0.3 on 2020-11-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.IntegerField(blank=True),
        ),
    ]
