# Generated by Django 3.0.3 on 2020-05-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200427_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('parent_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.Category')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
    ]
