# Generated by Django 3.0.3 on 2020-10-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_privatemessage_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='ticket',
        ),
    ]
