# Generated by Django 3.0.3 on 2020-11-12 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_remove_privatemessage_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSeenMessageInChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'last_seen_message_in_chat',
            },
        ),
    ]
