# Generated by Django 3.0.3 on 2020-11-12 07:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_lastseenmessageinchat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastSeenMessageInChat',
            new_name='LastSeenMessage',
        ),
        migrations.AlterModelTable(
            name='lastseenmessage',
            table='last_seen_message',
        ),
    ]
