# Generated by Django 3.0.3 on 2020-11-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20201112_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_systemic',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
