# Generated by Django 3.0.3 on 2020-04-10 18:56

from django.db import migrations, models
import django.db.models.deletion
import token_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.FileField(upload_to=token_auth.models.get_path_for_profile_photo)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNSURE', 'UNSURE')], default='UNSURE', max_length=10)),
                ('firebase_uid', models.TextField(blank=True, max_length=128)),
                ('firebase_token', models.TextField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='token_auth.ProfilePhoto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
