# Generated by Django 3.0.3 on 2020-04-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0002_auto_20200410_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firebase_token',
        ),
    ]
