# Generated by Django 3.0.3 on 2020-03-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0002_auto_20200330_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firebase_token',
            field=models.TextField(default='', max_length=255),
        ),
    ]
