# Generated by Django 3.0.3 on 2020-03-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0003_userprofile_firebase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firebase_token',
            field=models.TextField(max_length=255),
        ),
    ]
