# Generated by Django 3.0.3 on 2020-04-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0005_auto_20200419_2044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profilephoto',
            table='profile_photo',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
