# Generated by Django 3.0.3 on 2020-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20200330_2305'),
        ('token_auth', '0005_auto_20200330_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='events.Category'),
        ),
    ]
