# Generated by Django 3.0.3 on 2020-05-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0008_auto_20200511_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
