# Generated by Django 3.0.3 on 2020-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0010_userprofile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
