# Generated by Django 3.0.3 on 2020-05-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0012_auto_20200511_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
