# Generated by Django 3.0.3 on 2020-05-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0013_auto_20200511_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
