# Generated by Django 3.0.3 on 2020-05-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0017_auto_20200514_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
