# Generated by Django 3.0.3 on 2020-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200514_1442'),
        ('token_auth', '0020_auto_20200515_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='common.SubCategory'),
        ),
    ]
