# Generated by Django 3.0.3 on 2020-05-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200515_2052'),
        ('token_auth', '0021_auto_20200515_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='categories',
            field=models.ManyToManyField(to='common.SubCategory'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vk_token',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
