# Generated by Django 3.0.3 on 2020-05-15 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200515_2052'),
        ('token_auth', '0023_remove_userprofile_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SubCategory')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile_categories',
                'unique_together': {('user_profile', 'category')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='categories',
            field=models.ManyToManyField(through='token_auth.UserProfileCategories', to='common.SubCategory'),
        ),
    ]
