# Generated by Django 3.0.3 on 2020-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0024_auto_20200515_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
