# Generated by Django 3.0.3 on 2020-05-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0025_userprofile_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
