# Generated by Django 3.0.3 on 2020-05-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0026_remove_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
