# Generated by Django 3.0.3 on 2020-05-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0027_auto_20200517_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
