# Generated by Django 3.0.3 on 2020-05-17 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_auto_20200515_2052'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('sold', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='tickets', to='common.Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
