# Generated by Django 3.0.3 on 2020-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('address', models.TextField()),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('zone', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='tickets', to='common.Category')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
