# Generated by Django 3.0.3 on 2020-06-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200610_1435'),
        ('tickets', '0002_ticket_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='address',
        ),
        migrations.AddField(
            model_name='ticket',
            name='geo_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.GeoPoint'),
            preserve_default=False,
        ),
    ]
