# Generated by Django 3.0.3 on 2020-04-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200427_2025'),
        ('tickets', '0002_auto_20200427_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='common.Category'),
        ),
    ]
