# Generated by Django 3.0.3 on 2020-05-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.TextField(default='ldflef'),
            preserve_default=False,
        ),
    ]
