# Generated by Django 3.0.3 on 2020-05-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200519_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
