# Generated by Django 3.0.3 on 2020-05-22 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200519_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='place',
        ),
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.TextField(default=datetime.datetime(2020, 5, 22, 12, 59, 23, 399138, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
