# Generated by Django 3.0.3 on 2020-06-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='message',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofilewarning',
            name='complaint',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='moderator.Complaint'),
            preserve_default=False,
        ),
    ]
