# Generated by Django 3.0.3 on 2020-06-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_auto_20200602_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user_profile',
            new_name='suspected',
        ),
    ]
